npmbuildtools
=============
:Author: Thorben Wolkersdorfer
:Email: <thorbenw@nbb.com>
:AuthorUrl: https://www.notebooksbilliger.de/
:Date: 2020-03-09
:Revision: 1.1.0
:License: MIT

- Version {revision}
- Licensed under the {license} license.

Tools for use with npm package management.

Usage
-----
Specify the tools in the `scripts` section of the `package.json` package file, like so:
[source,json]
----
{
    "name": "myPackage",
    "version": "1.0.0",
    "description": "Example package",
    "main": "index.js",
    "scripts": {
      "postpack": "node -e \"require('buildtools').PostPack([ [ './node_modules/@nbb.com/buildtools/lib/clean-package-elements', 'scripts.postpack', 'directories.test' ] ])\"",
      "postinstall": "node ./node_modules/@nbb.com/buildtools/lib/check-global-deps npm typescript"
    },
    "directories": {
        "test": "./test"
    }
}
----

Contributing
------------
Yes, of course, please see link:doc/Contribution.adoc[]!

Features
--------
This is a collection of functions that turned out to be useful during the development, testing and publishing of node packages.

Console Capturing
~~~~~~~~~~~~~~~~~
During tests, output from the tested functions are sometimes unwanted. Most of the time, a plain and simple
output is required that just tells if all tests have completed successfully or not. *npmbuildtools* provide a
set of functions and properties to accomplish this: The `ConsoleCaptureStart()` and `ConsoleCaptureStop()`
functions allow for suppressing output while capturing it in the `stdout` and `stderr` properties.

If the `DebugMode` property evaluates to `true`, captured output will automatically be forwarded to the console, otherwise it will be suppressed.

To enforce proper capturing start and stop, it cannot be started or stopped more than once at a time (i.e.
if you start or stop capturing, and then try to start or stop captuing another time, an error will be genereated). If capturing has been started, it must be stopped first, before you can start capturing again.
If capturing has been stopped, it must be started first before you can stop it again.

Due to all output being captured, you may of course also miss output of severe errors that stop the whole
testing process, and therefore don't recognize something is wrong. The following pattern(s) have been tried
while using mocha for unit testing and are most promising to get everything right.

If you expect a function to fail, use the classic pattern and place the capture support function accordingly:
[source,javascript]
----
const btools = require('@nbb.com/npmbuildtools');

describe('your test', function() {
    it('should fail', function(done) {

        btools.ConsoleCaptureStart();  // start capturing
        try {
            functionToTest(); // call the function you expect to fail
            assert.fail(`should have failed`); // if it unexpectedly succeeds, fail on your own
            // do NOT stop capturing here because the `catch` block will be called anyway!
        } catch(err) {
            btools.ConsoleCaptureStop(); // stop capturing before doing anything else
            // do your asserts here
            assert.ok(err instanceof Error, `'err' should be an Error object`);
            assert.equal(err.message, `expected message`, `Error message should be`)
        }

        done();
    });
});
----

If you expect a function to succeed, you also have to use the classic 'fail' pattern because if the function
fails unexpectedly, or even crashed the whole test run, you wouldn't get aware of it:
[source,javascript]
----
const btools = require('@nbb.com/npmbuildtools');

describe('your test', function() {
    it('should succeed', function(done) {

        btools.ConsoleCaptureStart();  // start capturing
        try {
            functionToTest(); // call the function you expect to fail
            btools.ConsoleCaptureStop(); // stop capturing regularly because the `catch` block won't be called
        } catch(err) {
            btools.ConsoleCaptureStop(); // stop capturing before doing anything else
            throw err; // now throw the error
        }

        done();
    });
});
----

